# This is a basic workflow to help you get started with Actions

name: PLAYGROUND

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "danger-github-conf*"
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: IF TAG -> configure Semver in cargo.toml and tauri.conf.json files with ref_type - ${{ github.ref_type }} and ref_name - ${{github.ref_name}}
        if: github.ref_type == 'tag'
        run: node configure-versions.js ${{ github.ref_name }}

      - name: IF BRANCH -> configure Semver in cargo.toml and tauri.conf.json files
        if: github.ref_type == 'branch'
        run: |
          # Get the tag description
          TAG_DESCRIPTION=$(git describe --tags --always)

          # Output the tag description for logging
          echo "Tag description is $TAG_DESCRIPTION"

          node configure-versions.js "$TAG_DESCRIPTION"
