name: infinity key release
# never use `Build Infinity-key Release Artifacts` again as name because of build hickups

on:
  workflow_dispatch:
  release:
    types: [published]
env:
  CARGO_TERM_QUIET: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/download-build-assets.yml
    with:
      secrets: inherit
