name: infinity key release
# never use `Build Infinity-key Release Artifacts` again as name because of build hickups

on:
  workflow_dispatch:
  release:
    types: [published]
env:
  CARGO_TERM_QUIET: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
  APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

jobs:
  call-reusable-workflow:
    uses: ./download-build-assets.yml
    with:
      secrets: inherit
